# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuddyBuildTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuddyBuildTest
  pod 'MCNumberLabel'

  target 'BuddyBuildTestIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuddyBuildTestPerformanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuddyBuildTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuddyBuildTestUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
